### ISSUE TITLE
It takes a long time to train the model

### ISSUE THREAD

**Issue by mikel-hernandezj** [clementchadebec/pyraug#3]
I am trying to train a RHVAE model for data augmentation and the model starts training but it takes a long time training and do not see any results. I do not know if is an error from my dataset, computer or from the library. Could you help me?

**Comment by clementchadebec** [comment]
Hello @mikel-hernandezj, thanks for your interest in Pyraug and for opening this issue. This is true that the model may take some time to be trained. To reduce this you may want to reduce the 'max_epochs' argument in your TrainingConfig instance. You can also decrease the number of leapfrog steps used in the model by amending the RHVAEConfig instance and build your model as such
```python
from pyraug.models import RHVAE
from pyraug.models.rhvae import RHVAEConfig
model_config = RHVAEConfig(
    input_dim=int(input_dim),
    n_lf=1
 ) 
model = RHVAE(model_config)
```
Then you can pass it to the TrainingPipeline instance as explained in the notebooks tutorials. 

```python
from pyraug.pipelines import TrainingPipeline
pipeline = TrainingPipeline(
    model=model,
    training_config=your_training_config
)
pipeline(
    train_data=dataset_to_augment,
    log_output_dir='output_logs'
)
```

As to the training follow-up, as soon as the training is started (and if you set the `log_output_dir` argument to something e.g. `output_logs`  and not to None when calling the TrainingPipeline) you should be able to follow the training in the  `output_logs` folder in the `.log`  file.

Hope this helps :)

**Comment by clementchadebec** [comment]
Hello, 

I assume that my previous answer addressed your concern and so I am closing this issue.
Do not hesitate to reopen it if needed.

Best
