### ISSUE TITLE
How to make the VAE conditional on a label?

### ISSUE THREAD

**Issue by emilythyrum** [clementchadebec/pyraug#8]
Hi,

I was wondering how I can make the VAE conditional on a label. To be more clear, I know how to implement a conditional VAE without using pyraug, but I am not sure how to incorporate the conditional part into this library's training pipeline. Would you give an example if this can be done with the current version please?

**Comment by clementchadebec** [comment]
Hi @emilythyrum,

Unfortunately, it is not possible to include any conditioning to the model implemented in Pyraug since it does not support it. The best way to augment a multi-label dataset is to train one model per label.

Best,

Clément
